
LeagueName: "Settlers"
SearchSuffix: 
  - "yWlV6qeHR" # Death Rush Amethyst Ring, 2s, 40c https://www.pathofexile.com/trade/search/Necropolis/yWlV6qeHR
  - "YV6GRq6FY" # Death Rush Amethyst Ring, 3s, 70c https://www.pathofexile.com/trade/search/Necropolis/YV6GRq6FY
  - "8YlwWgZiV" # Deafening Essence of Wrath 3c https://www.pathofexile.com/trade/search/Necropolis/8YlwWgZiV
  - "eMY9mqrfL" # Essence Scarab of Ascent, 10c https://www.pathofexile.com/trade/search/Necropolis/eMY9mqrfL
  - "b0BGPgdfL" # The Brass Dome Gladiator Plate, +5%, 80c https://www.pathofexile.com/trade/search/Necropolis/b0BGPgdfL
  - "V4LlpVXtp" # The Brass Dome Gladiator Plate, +4%, 25c https://www.pathofexile.com/trade/search/Necropolis/V4LlpVXtp
  - "OlWOdPztE" # Darkness Enthroned Stygian Vise, +90%, 60c https://www.pathofexile.com/trade/search/Necropolis/OlWOdPztE
  - "Q42ZlzeCw" # Large Cluster Jewel, 8, 12% increased Physical Damage, ilvl 50-67 https://www.pathofexile.com/trade/search/Necropolis/Q42ZlzeCw
  - "20dqXO0ck" # Large Cluster Jewel, 8, 12% increased Chaos Damage, ilvl 50-67 https://www.pathofexile.com/trade/search/Necropolis/20dqXO0ck
  - "4oD5ZYvT9" # Sunblast Cloth Belt, -70%, 75c https://www.pathofexile.com/trade/search/Necropolis/4oD5ZYvT9
  #- "MlOvmYGcJ" # FORTUNATE 19 c https://www.pathofexile.com/trade/search/Necropolis/MlOvmYGcJ
Cookie: "YOUR COOKIE HERE"
PlayNotificationSoundOnWhisper: true