
LeagueName: "Necropolis"
SearchSuffix: 
  - "yWlV6qeHR" # Death Rush Amethyst Ring, 2s, 40c
  - "YV6GRq6FY" # Death Rush Amethyst Ring, 3s, 70c
  - "8YlwWgZiV" # Deafening Essence of Wrath 3c
  - "eMY9mqrfL" # Essence Scarab of Ascent, 10c
  - "b0BGPgdfL" # The Brass Dome Gladiator Plate, +5%, 80c
  - "V4LlpVXtp" # The Brass Dome Gladiator Plate, +4%, 25c
  - "rZDBVq4HQ" # Darkness Enthroned Stygian Vise, +80%, 30c
  - "Q42ZlzeCw" # Large Cluster Jewel, 8, 12% increased Physical Damage, ilvl 50-67
  - "20dqXO0ck" # Large Cluster Jewel, 8, 12% increased Chaos Damage, ilvl 50-67
  - "4oD5ZYvT9" # Sunblast Cloth Belt, -70%, 75c 
Cookie: "YOUR COOKIE HERE"
PlayNotificationSoundOnWhisper: true